### ISSUE TITLE
AGP Soft launch readiness tracking

### ISSUE THREAD

**Issue by longhotsummer** [laws-africa/peachjam#182]
For soft launch of agp.africanlii.org:

# Functionality

* [x] finalise text copy
* [x] finalise document type names
* [x] finalise page layouts
* [x] finalise functionality
* [x] finalise translations (see #176) 

# Content

* [x] ensure required content has been imported
* [x] #235
* [x] ensure document and site permissions are set and observed

**Comment by longhotsummer** [comment]
I've added a "judgment editors" permissions group that allows CRUD for judgments.
