### ISSUE TITLE
Lawlibrary migration high level tracking

### ISSUE THREAD

**Issue by longhotsummer** [laws-africa/peachjam#183]
Migration of lawlibrary.org.za to peachjam. We want the site to visually be similar to the existing site, to avoid jarring users.

# Plumbing

* [x] new liiweb django project inside this repo
* [x] new lawlibrary django project inside this repo that builds on liiweb
* [x] separate elasticsearch document index

# Page symmetry

* [x] listing pages match
* [x] detail pages match
* [x] homepage matches

# Data migration

* [ ] migrate existing judgments - #328 
* [x] #369
* [x] mimic or redirect URLs?

# Content

* [x] all required content types are supported
* [x] ability for users to upload and edit content
* [x] content is imported from indigo
* [x] MNCs are generated automatically

# Look and feel

* [x] styling and branding
* [x] copywriting

**Comment by longhotsummer** [comment]
Closing in favour of remaining issues
